// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ

package coordinator

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	hacatalog "github.com/SukramJ/go-ha-catalog"
	"github.com/SukramJ/go-hamqtt/discovery"
	hamodel "github.com/SukramJ/go-hamqtt/model"
	"github.com/SukramJ/go-hamqtt/publisher"

	"github.com/SukramJ/go-mqtt"

	daikinmodel "github.com/SukramJ/go-daikin2mqtt/internal/daikin/model"
	"github.com/SukramJ/go-daikin2mqtt/internal/hass"
	"github.com/SukramJ/go-daikin2mqtt/internal/process"
)

// ADR 0070 phase 8 step 4 — the decisive experiment.
//
// These tests prove that go-hamqtt reproduces this bridge's published discovery
// payloads BYTE FOR BYTE, while publishing nothing.
//
// What "byte for byte" means here is what the pin itself means by it: the
// comparison is on canonical re-encoding, the same standard
// TestPublishedSurfaceGolden holds. Both sides go through encoding/json, which
// sorts object keys, so key ORDER cannot make a run pass or fail — the bridge
// marshals a struct in field order and the library marshals a map, and neither
// order is a fact Home Assistant can see. Every key, every value and every
// topic is compared exactly.
//
// The comparison runs against the GOLDEN FILES — the twelve scenarios as
// #75/#76 left them — not against the builders they guard. No golden is
// regenerated by anything in this file: -update-surface-golden is not
// reachable from here, and none of the twelve SHA-256 literals in
// goldenDigests moves.
//
// One key group is reproduced SEMANTICALLY rather than literally, named once
// here and nowhere else: the library's default path renders availability as a
// LIST and this bridge publishes the singular `availability_topic` with
// top-level payloads. Home Assistant accepts both spellings identically and an
// entity's registry keys are unaffected. hass.singularAvailability performs
// that one re-spelling, and it refuses anything that is not exactly one
// bridge-level source — so model.BridgeOnly stays load-bearing (decision F8).

// --- the inputs ------------------------------------------------------------

// hamqttInputs is one scenario's discovery inputs: exactly what
// Coordinator.pollOnce hands hass.Discovery.Publish, plus the schedule list it
// hands PublishSchedules.
type hamqttInputs struct {
	points       []process.Point
	infos        map[string]hass.DeviceInfo
	climateInfos map[string]hass.ClimateInfo
	schedules    []hass.ScheduleInfo
	configURL    string
	disc         *hass.Discovery
}

// buildHamqttInputs runs a scenario exactly as buildSurface does — the same
// coordinator, the same two poll cycles, the same real catalogue and fixtures —
// and then re-derives the discovery inputs from the warmed caches.
//
// The re-derivation is NOT taken on trust: TestHamqttInputsReproduceThePublished
// ConfigTopics feeds these very inputs back through the daemon's own builders
// and requires the result to equal the golden's config plane exactly. A
// divergence in the derivation therefore fails loudly instead of quietly
// weakening the byte-equality proof that rests on it.
func buildHamqttInputs(t *testing.T, sc surfaceScenario) hamqttInputs {
	t.Helper()

	raw, err := os.ReadFile(sc.fixture)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	cat := loadRealCatalog(t)

	rec := &recorderMQTT{}
	cfg := scenarioConfig(sc)
	disc := hass.New(cfg.HASSBaseTopic, cfg.MQTTTopic, cfg.Language, rec)
	c := New(Deps{
		Cfg: cfg, Client: &stubCloud{devices: raw}, MQTT: rec, Catalog: cat,
		HASS: disc, Logger: slog.New(slog.DiscardHandler), Clock: func() time.Time { return goldenClock },
	})
	if sc.local {
		c.deps.FaikinMQTT = rec
	}
	if sc.sched != nil {
		c.AttachScheduler(&stubScheduler{doc: sc.sched})
	}

	ctx, cancel := context.WithCancel(t.Context())
	defer cancel()
	c.PublishOnline(ctx)
	c.pollOnce(ctx)
	c.pollOnce(ctx)

	devices, err := daikinmodel.ParseDevices(raw)
	if err != nil {
		t.Fatalf("parse devices: %v", err)
	}
	points := process.ResolveAt(devices, cat, goldenClock)
	if cfg.LocalEnabled() {
		points = append(points, c.localOnlyPoints(devices, points)...)
	}
	points = append(points, c.refreshPoints(devices)...)
	points = append(points, c.schedulePoints(devices)...)

	infos := deviceInfos(devices)
	c.applyFaikinConfigURLs(infos)

	in := hamqttInputs{
		points:       points,
		infos:        infos,
		climateInfos: climateInfos(devices, cfg.Language),
		configURL:    c.webConfigURL(),
		disc:         disc,
	}
	if sc.sched != nil {
		for i := range sc.sched.Schedules {
			s := &sc.sched.Schedules[i]
			in.schedules = append(in.schedules, hass.ScheduleInfo{ID: s.ID, Name: s.Name})
		}
	}
	return in
}

// --- the golden side -------------------------------------------------------

// goldenConfigs returns a scenario's discovery config plane as it is pinned on
// disk: topic -> canonical encoding of the payload. It reads the golden FILE
// and never the builders.
func goldenConfigs(t *testing.T, scenario string) map[string]string {
	t.Helper()
	doc := readGolden(t, filepath.Join("testdata", "surface", scenario+".json"))
	out := map[string]string{}
	for _, m := range doc.Messages {
		if !isConfigTopic(m.Topic) {
			continue
		}
		if m.JSON == nil {
			t.Fatalf("%s: config message %q carries no decoded payload", scenario, m.Topic)
		}
		b, err := json.Marshal(m.JSON)
		if err != nil {
			t.Fatalf("canonical encode %q: %v", m.Topic, err)
		}
		if _, dup := out[m.Topic]; dup {
			t.Fatalf("%s: golden holds %q twice", scenario, m.Topic)
		}
		out[m.Topic] = string(b)
	}
	return out
}

func isConfigTopic(topic string) bool {
	return strings.HasPrefix(topic, "homeassistant/") && strings.HasSuffix(topic, "/config")
}

// canonical re-encodes a rendered body so both sides are compared on the same
// footing: sorted keys, no formatting.
func canonical(t *testing.T, body []byte) string {
	t.Helper()
	var obj map[string]any
	if err := json.Unmarshal(body, &obj); err != nil {
		t.Fatalf("decode rendered body: %v", err)
	}
	b, err := json.Marshal(obj)
	if err != nil {
		t.Fatalf("canonical encode: %v", err)
	}
	return string(b)
}

// renderHamqtt renders a scenario's whole discovery plane through go-hamqtt.
func renderHamqtt(t *testing.T, in hamqttInputs) []hass.HamqttConfig {
	t.Helper()
	got, err := in.disc.RenderHamqtt(in.points, in.infos, in.climateInfos)
	if err != nil {
		t.Fatalf("RenderHamqtt: %v", err)
	}
	if len(in.schedules) > 0 {
		sched, err := in.disc.RenderHamqttSchedules(in.schedules, in.configURL)
		if err != nil {
			t.Fatalf("RenderHamqttSchedules: %v", err)
		}
		got = append(got, sched...)
	}
	return got
}

// --- the experiment --------------------------------------------------------

// TestHamqttReproducesPublishedConfigs is the step-4 proof: every one of the
// 264 pinned discovery payloads across the twelve scenarios, rendered by
// go-hamqtt from a model.Device, its entities' descriptions and bindings, an
// own topic.Layout and an own discovery.Context — compared key by key against
// the golden FILES.
func TestHamqttReproducesPublishedConfigs(t *testing.T) {
	total, matched := 0, 0
	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			want := goldenConfigs(t, sc.name)
			in := buildHamqttInputs(t, sc)
			got := map[string]string{}
			for _, c := range renderHamqtt(t, in) {
				if _, dup := got[c.Topic]; dup {
					t.Fatalf("rendered %q twice", c.Topic)
				}
				got[c.Topic] = canonical(t, c.Body)
			}

			for _, topic := range sortedStringKeys(want) {
				total++
				g, ok := got[topic]
				if !ok {
					t.Errorf("- not rendered: %s", topic)
					continue
				}
				if g != want[topic] {
					t.Errorf("~ %s\n  golden   %s\n  rendered %s", topic, want[topic], g)
					continue
				}
				matched++
			}
			for _, topic := range sortedStringKeys(got) {
				if _, ok := want[topic]; !ok {
					t.Errorf("+ rendered a config the bridge does not publish: %s", topic)
				}
			}
			if len(want) == 0 {
				t.Fatalf("scenario %q pins no discovery config at all", sc.name)
			}
		})
	}
	// The census is a Go literal so shrinking the proof is a declaration in
	// the review rather than a quietly smaller number.
	const wantTotal = 264
	if total != wantTotal {
		t.Errorf("compared %d pinned configs, want %d", total, wantTotal)
	}
	if matched != wantTotal {
		t.Errorf("reproduced %d of %d pinned configs byte for byte", matched, wantTotal)
	}
	t.Logf("go-hamqtt reproduced %d of %d pinned discovery payloads across %d scenarios",
		matched, total, len(surfaceScenarios()))
}

// TestHamqttInputsReproduceThePublishedConfigTopics is what makes the proof
// above non-circular.
//
// buildHamqttInputs re-derives the discovery inputs from a warmed coordinator
// rather than intercepting them, because intercepting them would mean changing
// the publish path. A re-derivation that quietly differed from what pollOnce
// actually hands hass.Discovery.Publish would render a different entity set and
// the byte-equality above would be proving something smaller than it claims.
//
// So the same inputs are fed back through the DAEMON's own builders, into a
// recorder, and the resulting config plane must equal the golden's exactly.
func TestHamqttInputsReproduceThePublishedConfigTopics(t *testing.T) {
	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			want := goldenConfigs(t, sc.name)
			in := buildHamqttInputs(t, sc)

			rec := &recorderMQTT{}
			cfg := scenarioConfig(sc)
			d := hass.New(cfg.HASSBaseTopic, cfg.MQTTTopic, cfg.Language, rec)
			if _, err := d.Publish(t.Context(), in.points, in.infos, in.climateInfos); err != nil {
				t.Fatalf("Publish: %v", err)
			}
			if len(in.schedules) > 0 {
				if _, err := d.PublishSchedules(t.Context(), in.schedules, in.configURL); err != nil {
					t.Fatalf("PublishSchedules: %v", err)
				}
			}

			got := map[string]string{}
			for _, m := range rec.snapshot() {
				if !isConfigTopic(m.Topic) {
					continue
				}
				b, err := json.Marshal(m.JSON)
				if err != nil {
					t.Fatal(err)
				}
				got[m.Topic] = string(b)
			}
			for _, topic := range sortedStringKeys(want) {
				if got[topic] != want[topic] {
					t.Errorf("re-derived inputs do not reproduce %s\n  golden %s\n  got    %s",
						topic, want[topic], got[topic])
				}
			}
			if len(got) != len(want) {
				t.Errorf("re-derived inputs produced %d configs, golden pins %d", len(got), len(want))
			}
		})
	}
}

// --- nothing reaches a broker ----------------------------------------------

// failingPublisher fails the test on contact. Step 4 changes no publish path
// and nothing new reaches a broker; this is the assertion of that, driven
// through every entry point the new path has.
type failingPublisher struct{ t *testing.T }

func (f failingPublisher) Publish(context.Context, string, []byte, mqtt.QoS, bool, ...mqtt.PublishOption) error {
	f.t.Errorf("the go-hamqtt rendering path published to the broker")
	return nil
}

func (f failingPublisher) Subscribe(context.Context, string, mqtt.QoS, mqtt.MessageHandler, ...mqtt.SubscribeOption) (mqtt.SubscribeResult, error) {
	f.t.Errorf("the go-hamqtt rendering path subscribed")
	return mqtt.SubscribeResult{}, nil
}

func (f failingPublisher) Unsubscribe(context.Context, string) error { return nil }

func TestHamqttRenderPathPublishesNothing(t *testing.T) {
	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			in := buildHamqttInputs(t, sc)
			cfg := scenarioConfig(sc)
			d := hass.New(cfg.HASSBaseTopic, cfg.MQTTTopic, cfg.Language, failingPublisher{t: t})
			if _, err := d.RenderHamqtt(in.points, in.infos, in.climateInfos); err != nil {
				t.Fatalf("RenderHamqtt: %v", err)
			}
			if _, err := d.RenderHamqttSchedules(in.schedules, in.configURL); err != nil {
				t.Fatalf("RenderHamqttSchedules: %v", err)
			}
			if _, err := d.HamqttModel(in.points, in.infos, in.climateInfos); err != nil {
				t.Fatalf("HamqttModel: %v", err)
			}
			if _, err := d.HamqttScheduleModel(in.schedules, in.configURL); err != nil {
				t.Fatalf("HamqttScheduleModel: %v", err)
			}
		})
	}
}

// --- the legacy topic form --------------------------------------------------

// TestHamqttLegacyTopicForm settles, against the PINNED topics rather than
// against this bridge's own ConfigTopic, which publisher.LegacyTopicFunc step 6
// must state in publisher.Config.LegacyEntityTopics.
//
// It is the single fact step 6 turns on. Getting it wrong is silent and total:
// a form that retracts none of the retained per-entity configs leaves the
// device bundle refused with one WARNING line as the only evidence, and
// Config.LegacyEntityTopics REPLACES the default rather than extending it — so
// saying nothing keeps the five-segment default, which retracts nothing here.
//
// All three forms the library ships are transcribed against all 264 pinned
// topics, so the test cannot pass vacuously: one must reproduce every topic and
// the other two must reproduce none.
func TestHamqttLegacyTopicForm(t *testing.T) {
	type candidate struct {
		name string
		fn   publisher.LegacyTopicFunc
	}
	candidates := []candidate{
		{"LegacyTopicByUniqueID", publisher.LegacyTopicByUniqueID},
		{"LegacyTopicWithNodeID (the library default)", publisher.LegacyTopicWithNodeID},
		{"LegacyTopicByObjectID", publisher.LegacyTopicByObjectID},
	}
	hits := make([]int, len(candidates))
	total := 0

	for _, sc := range surfaceScenarios() {
		want := goldenConfigs(t, sc.name)
		in := buildHamqttInputs(t, sc)
		devs, err := in.disc.HamqttModel(in.points, in.infos, in.climateInfos)
		if err != nil {
			t.Fatal(err)
		}
		schedDevs, err := in.disc.HamqttScheduleModel(in.schedules, in.configURL)
		if err != nil {
			t.Fatal(err)
		}
		ctx := in.disc.HamqttContext()
		for _, hd := range append(devs, schedDevs...) {
			for _, e := range hamodel.ApplySuppression(hd.Entities) {
				comp, err := discovery.RenderComponent(ctx, hd.Device, e, discovery.Origin{})
				if err != nil {
					t.Fatal(err)
				}
				le := publisher.LegacyEntity{
					Prefix:    "homeassistant",
					Platform:  string(comp.Platform),
					NodeID:    ctx.NodeID(hd.Device),
					ObjectID:  e.Key(),
					UniqueID:  comp.UniqueID,
					Component: comp,
				}
				total++
				for i, c := range candidates {
					if _, pinned := want[c.fn(le)]; pinned {
						hits[i]++
					}
				}
			}
		}
	}

	const wantTotal = 264
	if total != wantTotal {
		t.Fatalf("examined %d components, want %d", total, wantTotal)
	}
	if hits[0] != wantTotal {
		t.Errorf("%s reproduced %d of %d pinned config topics, want all",
			candidates[0].name, hits[0], wantTotal)
	}
	for i := 1; i < len(candidates); i++ {
		if hits[i] != 0 {
			t.Errorf("%s reproduced %d of %d pinned config topics, want none — "+
				"the verdict is only safe while the forms are distinguishable",
				candidates[i].name, hits[i], wantTotal)
		}
	}
	if hass.LegacyConfigTopicForm != "publisher."+strings.Fields(candidates[0].name)[0] {
		t.Errorf("hass.LegacyConfigTopicForm = %q, but %s is the form that reproduces the pinned topics",
			hass.LegacyConfigTopicForm, candidates[0].name)
	}
}

// --- Home Assistant's own schemas -------------------------------------------

// TestHamqttValidatesAgainstHomeAssistant runs every rendered payload through
// discovery.ValidateBody — Home Assistant's own MQTT discovery schemas, as
// go-ha-catalog carries them.
//
// This is a question this bridge had never asked of its own output. It matters
// beyond hygiene because of what step 6 does with the answer: a device bundle
// is validated as ONE document, and discovery.Validate reporting it Blocking()
// means the bundle publishes NOTHING AT ALL — so a single refused component
// costs the device its entire entity set rather than one entity. Home
// Assistant's own response to a refused per-entity config today is nothing
// visible at all: the config is dropped during schema validation, before the
// entity is constructed, with no error on the wire and no log line naming the
// cause.
func TestHamqttValidatesAgainstHomeAssistant(t *testing.T) {
	checked := 0
	refusals := map[string]int{}
	for _, sc := range surfaceScenarios() {
		in := buildHamqttInputs(t, sc)
		for _, c := range renderHamqtt(t, in) {
			var body map[string]any
			if err := json.Unmarshal(c.Body, &body); err != nil {
				t.Fatal(err)
			}
			checked++
			if err := discovery.ValidateBody(hacatalog.Platform(c.Platform), body); err != nil {
				var ve *discovery.ValidationError
				if errors.As(err, &ve) && !ve.Blocking() {
					continue // advisory only
				}
				refusals[fmt.Sprintf("%s: %v", c.Platform, err)]++
			}
		}
	}
	if checked != 264 {
		t.Errorf("validated %d payloads, want 264", checked)
	}
	if len(refusals) != 0 {
		for _, k := range sortedIntKeys(refusals) {
			t.Errorf("discovery.ValidateBody refuses %d payload(s): %s", refusals[k], k)
		}
	}
}

// TestHamqttBundleValidates renders each scenario's devices as device BUNDLES —
// the form step 6 publishes — and validates each as one document.
//
// It is the same schema check at the granularity that actually bites: a
// blocking bundle publishes nothing, so a fault that costs one entity on
// today's per-entity form costs a device all of its entities on the bundle.
//
// The bundle carries an origin block and the per-entity form does not. That is
// not an inconsistency: discovery.Validate makes origin.name a blocking issue
// on a bundle and optional on a per-entity config, and F12 (adding the origin
// block to the published payloads) is deliberately NOT part of this step —
// it would be a 264-row payload addition inside the byte-equality proof.
func TestHamqttBundleValidates(t *testing.T) {
	bundles, components := 0, 0
	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			in := buildHamqttInputs(t, sc)
			devs, err := in.disc.HamqttModel(in.points, in.infos, in.climateInfos)
			if err != nil {
				t.Fatal(err)
			}
			schedDevs, err := in.disc.HamqttScheduleModel(in.schedules, in.configURL)
			if err != nil {
				t.Fatal(err)
			}
			ctx := in.disc.HamqttContext()
			origin := discovery.Origin{Name: "go-daikin2mqtt"}
			for _, hd := range append(devs, schedDevs...) {
				b, err := discovery.Render(ctx, hd.Device, hd.Entities, origin)
				if err != nil {
					t.Fatalf("Render bundle for %s: %v", hd.Device.UID(), err)
				}
				bundles++
				components += len(b.Components)
				if err := discovery.Validate(b); err != nil {
					var ve *discovery.ValidationError
					if errors.As(err, &ve) && !ve.Blocking() {
						t.Logf("advisory on %s: %v", hd.Device.UID(), err)
						continue
					}
					t.Errorf("discovery.Validate refuses the bundle for %s: %v", hd.Device.UID(), err)
				}
			}
		})
	}
	t.Logf("validated %d device bundles carrying %d components", bundles, components)
}

// TestHamqttBundledClimateReadsASiblingComponentsTopic narrows — as far as it
// can be narrowed without a live Home Assistant — the one open question the
// measurement left gating step 6 (§3.4, third item).
//
// The composite climate's current_temperature_topic points at a state topic
// that belongs to ANOTHER component of the same device: room_temperature is not
// among the three entities the composite suppresses, so in a device bundle the
// two sit side by side and one reads the other's topic. Whether Home Assistant
// objects to that inside one document is a runtime question and stays one.
//
// What this settles is everything below it: the shape really does occur (it is
// not hypothetical), the library renders it without complaint, and Home
// Assistant's own discovery SCHEMAS — which is what discovery.Validate checks —
// do not refuse it. So what remains to be tested against HA 2026.9 is the
// runtime behaviour alone, on a bundle this test proves is buildable.
func TestHamqttBundledClimateReadsASiblingComponentsTopic(t *testing.T) {
	in := buildHamqttInputs(t, surfaceScenarios()[8]) // multisplit.en
	devs, err := in.disc.HamqttModel(in.points, in.infos, in.climateInfos)
	if err != nil {
		t.Fatal(err)
	}
	ctx := in.disc.HamqttContext()
	found := 0
	for _, hd := range devs {
		b, err := discovery.Render(ctx, hd.Device, hd.Entities, discovery.Origin{Name: "go-daikin2mqtt"})
		if err != nil {
			t.Fatal(err)
		}
		climate, ok := b.Components["climate"]
		if !ok {
			continue
		}
		raw, err := json.Marshal(climate)
		if err != nil {
			t.Fatal(err)
		}
		var body map[string]any
		if err := json.Unmarshal(raw, &body); err != nil {
			t.Fatal(err)
		}
		want, _ := body["current_temperature_topic"].(string)
		if want == "" {
			t.Fatalf("%s: the composite climate names no current_temperature_topic", hd.Device.UID())
		}
		sibling, ok := b.Components["room_temperature"]
		if !ok {
			t.Fatalf("%s: room_temperature is not a sibling component; the shape has changed", hd.Device.UID())
		}
		if sibling.StateTopic != want {
			t.Errorf("%s: climate reads %q, sibling publishes %q", hd.Device.UID(), want, sibling.StateTopic)
		}
		// It is a sibling, not a suppressed entity: the composite suppresses
		// power, operation_mode and the setpoint, and none of those is this.
		for _, suppressed := range []string{"power", "operation_mode", "temperature_setpoint"} {
			if _, present := b.Components[suppressed]; present {
				t.Errorf("%s: %q survived suppression", hd.Device.UID(), suppressed)
			}
		}
		if err := discovery.Validate(b); err != nil {
			t.Errorf("%s: Home Assistant's schemas refuse the bundle: %v", hd.Device.UID(), err)
		}
		found++
	}
	if found != 2 {
		t.Fatalf("found %d bundled composites on the two-indoor multi-split, want 2", found)
	}
}

// --- helpers ---------------------------------------------------------------

func sortedStringKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedIntKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
